
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DAL_EF
{

using System;
    using System.Collections.Generic;
    
public partial class Invoice
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Invoice()
    {

        this.Agreements = new HashSet<Agreement>();

        this.InvoiceItems = new HashSet<InvoiceItem>();

        this.Notices = new HashSet<Notice>();

    }


    public int InvoiceId { get; set; }

    public int AgreementId { get; set; }

    public string InvoiceNumber { get; set; }

    public int PersonId { get; set; }

    public int OrganizationId { get; set; }

    public System.DateTime CreateDate { get; set; }

    public System.DateTime InvoiceDate { get; set; }

    public int DueDays { get; set; }

    public System.DateTime DueDate { get; set; }

    public double Amount { get; set; }

    public Nullable<double> DiscountAmount { get; set; }

    public Nullable<int> DiscountPercent { get; set; }

    public int Vat { get; set; }

    public double VatAmount { get; set; }

    public double TotalAmount { get; set; }

    public string Currency { get; set; }

    public double CurrencyRate { get; set; }

    public string Disclaimer { get; set; }

    public bool IsPaid { get; set; }

    public Nullable<System.DateTime> PaidDate { get; set; }

    public bool IsActive { get; set; }

    public bool IsDeleted { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Agreement> Agreements { get; set; }

    public virtual Agreement Agreement { get; set; }

    public virtual Organization Organization { get; set; }

    public virtual Person Person { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<InvoiceItem> InvoiceItems { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Notice> Notices { get; set; }

}

}
