
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DAL_EF
{

using System;
    using System.Collections.Generic;
    
public partial class InvoiceItem
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public InvoiceItem()
    {

        this.Offers = new HashSet<Offer>();

    }


    public int InvoiceItemId { get; set; }

    public string ItemName { get; set; }

    public int InvoiceId { get; set; }

    public double UnitPrice { get; set; }

    public int Vat { get; set; }

    public double VatUnitPrice { get; set; }

    public int Quantity { get; set; }

    public double PriceIncludingVat { get; set; }

    public double PriceExcludingVat { get; set; }

    public double VatAmount { get; set; }

    public Nullable<double> DiscountAmount { get; set; }

    public Nullable<double> DiscountPersentage { get; set; }

    public bool IsActive { get; set; }

    public bool IsDeleted { get; set; }



    public virtual Invoice Invoice { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Offer> Offers { get; set; }

}

}
