
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DAL_EF
{

using System;
    using System.Collections.Generic;
    
public partial class Notice
{

    public int NoticeId { get; set; }

    public string NoticeText { get; set; }

    public int NoticeNumber { get; set; }

    public System.DateTime NoticeDate { get; set; }

    public int InvoiceId { get; set; }

    public Nullable<int> PersonId { get; set; }

    public Nullable<int> OrganizationId { get; set; }

    public bool IsActive { get; set; }

    public bool IsDeleted { get; set; }



    public virtual Invoice Invoice { get; set; }

    public virtual Organization Organization { get; set; }

    public virtual Person Person { get; set; }

}

}
