
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DAL_EF
{

using System;
    using System.Collections.Generic;
    
public partial class Organization
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Organization()
    {

        this.Invoices = new HashSet<Invoice>();

        this.Notices = new HashSet<Notice>();

        this.Offers = new HashSet<Offer>();

    }


    public int OrganizationId { get; set; }

    public string OrganizationName { get; set; }

    public string CompanyId { get; set; }

    public string VatNumber { get; set; }

    public string Description { get; set; }

    public string Email { get; set; }

    public string PhoneNumber { get; set; }

    public Nullable<int> Type { get; set; }

    public int AddressId { get; set; }

    public bool IsActive { get; set; }

    public bool IsDeleted { get; set; }



    public virtual Address Address { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Invoice> Invoices { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Notice> Notices { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Offer> Offers { get; set; }

}

}
