//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADO.NET
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DMS_Entities : DbContext
    {
        public DMS_Entities()
            : base("name=DMS_Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Address> Addresses { get; set; }
        public virtual DbSet<Agreement> Agreements { get; set; }
        public virtual DbSet<Invoice> Invoices { get; set; }
        public virtual DbSet<InvoiceItem> InvoiceItems { get; set; }
        public virtual DbSet<Notice> Notices { get; set; }
        public virtual DbSet<Offer> Offers { get; set; }
        public virtual DbSet<Organization> Organizations { get; set; }
        public virtual DbSet<Person> People { get; set; }
    
        public virtual ObjectResult<spPerson_GetAll_Result> spPerson_GetAll()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spPerson_GetAll_Result>("spPerson_GetAll");
        }
    
        public virtual ObjectResult<spPerson_GetLastName_Result> spPerson_GetLastName(string personLastName)
        {
            var personLastNameParameter = personLastName != null ?
                new ObjectParameter("PersonLastName", personLastName) :
                new ObjectParameter("PersonLastName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spPerson_GetLastName_Result>("spPerson_GetLastName", personLastNameParameter);
        }
    
        public virtual int spPerson_UpdateCity(string city, Nullable<int> addressId)
        {
            var cityParameter = city != null ?
                new ObjectParameter("City", city) :
                new ObjectParameter("City", typeof(string));
    
            var addressIdParameter = addressId.HasValue ?
                new ObjectParameter("AddressId", addressId) :
                new ObjectParameter("AddressId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spPerson_UpdateCity", cityParameter, addressIdParameter);
        }
    
        public virtual int spPerson_UpdateEmail(string email, Nullable<int> idNumber)
        {
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            var idNumberParameter = idNumber.HasValue ?
                new ObjectParameter("IdNumber", idNumber) :
                new ObjectParameter("IdNumber", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spPerson_UpdateEmail", emailParameter, idNumberParameter);
        }
    
        public virtual ObjectResult<spPersonAddress_InnerJoin_Result> spPersonAddress_InnerJoin()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spPersonAddress_InnerJoin_Result>("spPersonAddress_InnerJoin");
        }
    }
}
