//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADO.NET
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notice
    {
        public int NoticeId { get; set; }
        public string NoticeText { get; set; }
        public Nullable<int> NoticeNumber { get; set; }
        public Nullable<System.DateTime> NoticeDate { get; set; }
        public int InvoiceId { get; set; }
        public int PersonId { get; set; }
        public int OrganizationId { get; set; }
        public int IsActive { get; set; }
        public int IsDeleted { get; set; }
    
        public virtual Invoice Invoice { get; set; }
    }
}
