//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADO.NET
{
    using System;
    using System.Collections.Generic;
    
    public partial class Offer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Offer()
        {
            this.Agreements = new HashSet<Agreement>();
        }
    
        public int OfferId { get; set; }
        public int OrganizationId { get; set; }
        public int PersonId { get; set; }
        public string OfferNumber { get; set; }
        public double Amount { get; set; }
        public Nullable<double> DiscountPercent { get; set; }
        public Nullable<double> DiscountAmount { get; set; }
        public Nullable<double> OfferAmount { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> ValidityDays { get; set; }
        public Nullable<System.DateTime> ValidityDate { get; set; }
        public string Disclaimer { get; set; }
        public string Title { get; set; }
        public string Subject { get; set; }
        public string Body { get; set; }
        public string Currency { get; set; }
        public Nullable<double> CurrencyRate { get; set; }
        public Nullable<int> Vat { get; set; }
        public Nullable<double> VatAmount { get; set; }
        public string ReasonForDeclining { get; set; }
        public Nullable<int> IsAccepted { get; set; }
        public Nullable<int> IsDeleted { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Agreement> Agreements { get; set; }
        public virtual Organization Organization { get; set; }
        public virtual Person Person { get; set; }
    }
}
